server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://smileway.co.kr:3306/bizmiso?characterEncoding=UTF-8&serverTimezone=UTC
    username: bizmiso
    password: Miso@7531
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create
      properties:
        hibernate:
          #          show_sql: true
          format_sql: true

logging:
  level:
    org.hibernate.SQL: debug